AWSTemplateFormatVersion: 2010-09-09

Description: 'This template creates a KMS encryption key, an encrypted S3 bucket using the encryption key'

Parameters:

    BucketName:
        AllowedPattern: '^[0-9a-z]+([0-9a-z]*[0-9a-z])*$'
        ConstraintDescription: 'Bucket name can include numbers, lowercase letters, and hyphens (-). It cannot start or end with a hyphen (-) or contain uppercase characters or underscores (_).'
        Default: ab3bucketbackup
        Description: 'S3 bucket name'
        Type: "String"
        
Resources:
    # KMS S3 encryption key
    s3Key:
      Type: AWS::KMS::Key
      Properties:
        KeyPolicy:
          Version: 2012-10-17
          Id: key-s3
          Statement:
            - Sid: Enable IAM User Permissions
              Effect: Allow
              Principal:
                AWS: !Join
                  - ''
                  - - 'arn:aws:iam::'
                    - !Ref 'AWS::AccountId'
                    - ':root'
              Action: 'kms:*'
              Resource: '*'
            - Sid: Allow VPC Flow Logs to use the key as well
              Effect: Allow
              Principal:
                Service:
                  - delivery.logs.amazonaws.com
              Action: 'kms:GenerateDataKey*'
              Resource: '*'
    s3KeyAlias:
      Type: AWS::KMS::Alias
      Properties:
        AliasName: alias/s3
        TargetKeyId:
          Ref: s3Key

    # Encrypted S3 Bucket for Storage
    S3GeneralBucket:
      Type: AWS::S3::Bucket
      UpdateReplacePolicy: Delete
      DeletionPolicy: Delete
      Properties:
        BucketName: !Ref BucketName
        BucketEncryption:
          ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              KMSMasterKeyID: !Sub 'arn:aws:kms:${AWS::Region}:${AWS::AccountId}:${s3KeyAlias}'
              SSEAlgorithm: 'aws:kms'
        PublicAccessBlockConfiguration:
            BlockPublicAcls: true
            BlockPublicPolicy: true
            IgnorePublicAcls: true
            RestrictPublicBuckets: true

Outputs:
    s3KeyAlias:
        Description: 'S3 KMS Key Alias'
        Value:
            Ref: 's3KeyAlias'
    S3GeneralBucket:
        Description: 'Encrypted S3 Bucket'
        Value:
            Ref: 'S3GeneralBucket'
